CREATE EXTERNAL SCHEMA spectrum 
FROM DATA CATALOG 
DATABASE 'spectrum_crime_db' 
IAM_ROLE 'arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_ROLE_NAME';

CREATE EXTERNAL TABLE spectrum.disct_info (
    DISTRICT_CODE INTEGER,
    DISTRICT_NAME VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP INTEGER,
    WEBSITE VARCHAR,
    PHONE VARCHAR,
    FAX VARCHAR,
    TTY VARCHAR,
    X_COORDINATE REAL,
    Y_COORDINATE REAL,
    LATITUDE REAL,
    LONGITUDE REAL,
    LOCATION VARCHAR
)
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE 
LOCATION 's3://YOUR_BUCKET_NAME/Spectrum-Store/';
