CREATE TABLE crimedata (
    id INTEGER,
    arrest VARCHAR,
    beat_num INTEGER,
    block VARCHAR,
    case_number VARCHAR,
    community_code INTEGER,
    date VARCHAR,
    date_of_update VARCHAR,
    district_code INTEGER,
    domestic VARCHAR,
    fbi_code VARCHAR,
    iucr_code VARCHAR,
    latitude REAL,
    location VARCHAR,
    location_desc VARCHAR,
    longitude REAL,
    ward_no INTEGER,
    x_coordinate INTEGER,
    y_coordinate INTEGER,
    year INTEGER
);
